export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const BLOCK_USER = "BLOCK_USER";
export const BLOCK_USERS = "BLOCK_USERS";
export const UNBLOCK_USER = "UNBLOCK_USER";
export const UNBLOCK_USERS = "UNBLOCK_USERS";
export const BLOCK_PROFILE_USER = "BLOCK_PROFILE_USER";
export const UNBLOCK_PROFILE_USER = "UNBLOCK_PROFILE_USER";
export const BLOCK_POST_USER = "BLOCK_POST_USER";
export const UNBLOCK_POST_USER = "UNBLOCK_POST_USER";
export const SUBSCRIBE_OR_BLOCK_POST_USER = "SUBSCRIBE_OR_BLOCK_POST_USER";
export const UNSUBSCRIBE_OR_UNBLOCK_POST_USER =
  "UNSUBSCRIBE_OR_UNBLOCK_POST_USER";
export const SUBSCRIBE_OR_BLOCK_PROFILE_USER =
  "SUBSCRIBE_OR_BLOCK_PROFILE_USER";
export const UNSUBSCRIBE_OR_UNBLOCK_PROFILE_USER =
  "UNSUBSCRIBE_OR_UNBLOCK_PROFILE_USER";
export const SUBSCRIBE_OR_BLOCK_POSTS_USERS = "SUBSCRIBE_OR_BLOCK_POSTS_USERS";
export const UNSUBSCRIBE_OR_UNBLOCK_POSTS_USERS =
  "UNSUBSCRIBE_OR_UNBLOCK_POSTS_USERS";
export const SUBSCRIBE_OR_BLOCK_RESPONSES_USERS =
  "SUBSCRIBE_OR_BLOCK_RESPONSES_USERS";
export const UNSUBSCRIBE_OR_UNBLOCK_RESPONSES_USERS =
  "UNSUBSCRIBE_OR_UNBLOCK_RESPONSES_USERS";
export const SUBSCRIBE_TO_FOLLOWER_USER = "SUBSCRIBE_TO_FOLLOWER_USER";
export const UNSUBSCRIBE_FROM_FOLLOWER_USER = "UNSUBSCRIBE_FROM_FOLLOWER_USER";
export const SUBSCRIBE_TO_NOTIFICATION_USER = "SUBSCRIBE_TO_NOTIFICATION_USER";
export const UNSUBSCRIBE_FROM_NOTIFICATION_USER =
  "UNSUBSCRIBE_FROM_NOTIFICATION_USER";
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_BLOCKED_USERS = "GET_BLOCKED_USERS";
export const GET_FOUND_USERS = "GET_FOUND_USERS";

export const GET_POST = "GET_POST";
export const GET_ALL_USER_POSTS = "GET_ALL_USER_POSTS";
export const GET_THREE_RANDOM_POSTS = "GET_THREE_RANDOM_POSTS";
export const LIKE_POST = "LIKE_POST";
export const UNLIKE_POST = "UNLIKE_POST";
export const GET_LIKED_POSTS = "GET_LIKED_POSTS";
export const GET_LIKED_RESPONSES = "GET_LIKED_RESPONSES";
export const GET_BOOKMARKED_POSTS = "GET_BOOKMARKED_POSTS";
export const BOOKMARK_POST = "BOOKMARK_POST";
export const DELETE_BOOKMARKED_POST = "DELETE_BOOKMARKED_POST";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const ADD_POST_REPORT = "ADD_POST_REPORT";
export const REMOVE_POST_REPORT = "REMOVE_POST_REPORT";
export const GET_FOUND_POSTS = "GET_FOUND_POSTS";
export const DELETE_POST = "DELETE_POST";

export const GET_TAG_POSTS = "GET_TAG_POSTS";
export const GET_FOUND_TAGS = "GET_FOUND_TAGS";

export const NEW_POST_RESPONSE = "NEW_POST_RESPONSE";
export const GET_POST_RESPONSES = "GET_POST_RESPONSES";
export const GET_USER_RESPONSES = "GET_USER_RESPONSES";
export const LIKE_RESPONSE = "LIKE_RESPONSE";
export const UNLIKE_RESPONSE = "UNLIKE_RESPONSE";
export const GET_BOOKMARKED_RESPONSES = "GET_BOOKMARKED_RESPONSES";
export const BOOKMARK_RESPONSE = "BOOKMARK_RESPONSE";
export const DELETE_RESPONSE_BOOKMARK = "DELETE_RESPONSE_BOOKMARK";
export const DELETE_BOOKMARKED_RESPONSE = "DELETE_BOOKMARKED_RESPONSE";
export const ADD_RESPONSE_REPORT = "ADD_RESPONSE_REPORT";
export const REMOVE_RESPONSE_REPORT = "REMOVE_RESPONSE_REPORT";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_ERROR = "GET_ERROR";

export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
export const ADD_ONE_MESSAGE_TO_FAVORITE = "ADD_ONE_MESSAGE_TO_FAVORITE";
export const ADD_MANY_MESSAGES_TO_FAVORITE = "ADD_MANY_MESSAGES_TO_FAVORITE";
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_CHATS = "GET_CHATS";
export const GET_UNREAD_CHATS_COUNT = "GET_UNREAD_CHATS_COUNT";
export const DELETE_MESSAGES = "DELETE_MESSAGES";
export const GET_FAVORITE_MESSAGES = "GET_FAVORITE_MESSAGES";

export const GET_ALL_NOTIFICATIONS = "GET_ALL_NOTIFICATIONS";
export const GET_LAST_NOTIFICATIONS = "GET_LAST_NOTIFICATIONS";
export const NEW_NOTIFICATION = "NEW_NOTIFICATION";
export const COUNT_NOTIFICATIONS = "COUNT_NOTIFICATIONS";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const DELETE_MESSAGE_NOTIFICATIONS = "DELETE_MESSAGE_NOTIFICATIONS";
export const READ_ALL_NOTIFICATIONS = "READ_ALL_NOTIFICATIONS";
export const READ_UNREAD_MESSAGES = "READ_UNREAD_MESSAGES";
